import fs from "node:fs/promises";
import path from "node:path";
import { DATA_DIR, saveDatasetExport } from "../repositories/local-store.js";

const SECRET_PATTERNS: Array<{ name: string; pattern: RegExp }> = [
  { name: "api_key", pattern: /\b(?:sk-[A-Za-z0-9_-]{16,}|AKIA[0-9A-Z]{16}|ghp_[A-Za-z0-9_]{20,}|xox[baprs]-[A-Za-z0-9-]{10,})\b/g },
  { name: "cookie", pattern: /\b(cookie|set-cookie|sessionid|connect\.sid)\s*[:=]\s*[^;\s]+/gi },
  { name: "bearer_token", pattern: /\bbearer\s+[A-Za-z0-9._~+/=-]{12,}/gi },
  { name: "private_key", pattern: /-----BEGIN (?:RSA |OPENSSH |EC |DSA )?PRIVATE KEY-----/g },
  { name: "email", pattern: /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi },
];

function sanitizeJson(value: unknown): { json: string; findings: Array<{ field: string; reason: string }> } {
  let json = JSON.stringify(value, null, 2);
  const findings: Array<{ field: string; reason: string }> = [];
  for (const item of SECRET_PATTERNS) {
    if (item.pattern.test(json)) {
      findings.push({ field: "github_ledger_payload", reason: item.name });
      json = json.replace(item.pattern, `[REDACTED_${item.name.toUpperCase()}]`);
    }
    item.pattern.lastIndex = 0;
  }
  return { json, findings };
}

function safeSegment(value: unknown): string {
  return String(value ?? "unknown")
    .replace(/[^a-zA-Z0-9_.-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80) || "unknown";
}

export async function writeGithubLedgerPayload(input: {
  payload: Record<string, unknown>;
  projectSlug?: string;
  dryRun?: boolean;
}) {
  const generatedAt = String(input.payload.generatedAt ?? new Date().toISOString());
  const date = generatedAt.slice(0, 10);
  const evalId = safeSegment(input.payload.promptVersionId ?? input.payload.promptId ?? Date.now());
  const projectSlug = safeSegment(input.projectSlug ?? input.payload.project ?? "ai-prompt-generator-v3");
  const dir = path.join(DATA_DIR, "github-ledger", projectSlug, date, evalId);
  await fs.mkdir(dir, { recursive: true });

  const sanitized = sanitizeJson(input.payload);
  const payloadPath = path.join(dir, "evaluation-ledger.json");
  const reportPath = path.join(dir, "quality-report.md");
  const diffPath = path.join(dir, "diff.patch");

  await fs.writeFile(payloadPath, `${sanitized.json}\n`, "utf8");
  const payload = input.payload as any;
  const report = [
    `# Evaluation Ledger ${evalId}`,
    "",
    `- Project: ${payload.project ?? projectSlug}`,
    `- Artifact type: ${payload.artifactType ?? "unknown"}`,
    `- Prompt: ${payload.promptId ?? "unknown"}`,
    `- Version: ${payload.promptVersionId ?? "unknown"}`,
    `- Human priority: ${payload.humanEvaluation?.priority ?? "highest"}`,
    `- Optimization triggered: ${payload.optimization?.triggered ? "yes" : "no"}`,
    `- Optimization status: ${payload.optimization?.status ?? "unknown"}`,
    `- Yellow items: ${Array.isArray(payload.yellowItems) ? payload.yellowItems.length : 0}`,
    `- Green below 9 items: ${Array.isArray(payload.greenBelowNineItems) ? payload.greenBelowNineItems.length : 0}`,
    `- Red items: ${Array.isArray(payload.redItems) ? payload.redItems.length : 0}`,
    "",
    "## Required Regression Commands",
    "",
    ...((payload.regression?.commands ?? []) as string[]).map((command) => `- \`${command}\``),
    "",
  ].join("\n");
  await fs.writeFile(reportPath, report, "utf8");
  await fs.writeFile(diffPath, "# Diff is generated by the optimization PR worker in production.\n", "utf8");

  const record = await saveDatasetExport({
    exportPath: payloadPath,
    itemCount: 1,
    privacyFindings: sanitized.findings,
  });

  return {
    ok: true as const,
    mode: input.dryRun ? "local_dry_run" : "local_ledger_ready_for_git_worker",
    ledgerDir: dir,
    payloadPath,
    reportPath,
    diffPath,
    privacyFindings: sanitized.findings,
    datasetExport: record,
    git: {
      required: true,
      suggestedBranch: `eval/${date}/${evalId}`,
      suggestedCommit: `eval(${projectSlug}): record evaluation ${evalId}`,
    },
  };
}
